version: '3'

networks:
  todo:
    driver: bridge

services:
  # swagger
  swagger:
    image: swaggerapi/swagger-ui:v3.0.5
    restart: always
    container_name: todo-swagger
    networks:
      todo:
        aliases:
          - swagger
